version: "3"

services:
  back:
    image: node:19.0.0-alpine
    user: node
    working_dir: /usr/src/server
    tty: true
    stdin_open: true
    ports:
      - 4000:4000
    volumes:
      - ./back:/usr/src/server

  front:
    image: node:19.0.0-alpine
    user: node
    working_dir: /usr/src/server
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./front:/usr/src/server

  postgresql:
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - target: 5432
        published: 5432
        protocol: tcp

  mongo:
      image: mongo
      ports:
        - 27017:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
      volumes:
        - ./SampleCollections:/usr/local/sampleCollections
        - db-data:/data/db
      working_dir: /usr/local/sampleCollections

  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
    - 5050:80
    depends_on:
    - postgresql

volumes:
  db-data: {}